### ISSUE TITLE
Docker ubuntu Illegal instruction SIGILL

### ISSUE THREAD

**Issue by nathanloisel** [bcmyers/argonautica#17]
I built my code on a docker container and executed it on the same docker image but not on the same machine. the docker image is `rustdocker/rust:stable`.
When I execute it and try to use verify or hash, I go this error.
```
Thread 30 "my_server" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffba3f1700 (LWP 18090)]
0x0000555555c71ab5 in blake2b_init_param ()
(gdb) backtrace
#0  0x0000555555c71ab5 in blake2b_init_param ()
#1  0x0000555555c71bd1 in blake2b_init ()
#2  0x0000555555c711ce in initial_hash ()
#3  0x0000555555c713de in initialize ()
#4  0x0000555555c7000a in argon2_ctx ()
#5  0x0000555555c6c42f in argonautica::hasher::Hasher::hash_raw::h5f24955622446a9c ()
#6  0x0000555555c67cd0 in argonautica::verifier::Verifier::verify::h5921130d7ebd73a7 ()
```

I have no idea why it's happening. To be honest, this problem is not in my area of expertise.

When I build the code and execute it on the same machine, there is no problem.

**Comment by nathanloisel** [comment]
Sorry problem fixed by removing "simd" in cargo.toml
